//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.1-05/30/2003 05:06 AM(java_re)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.23 at 11:11:43 GMT+01:00 
//

package freemind.clouds;

/**
 * Java content class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this java content object.
 * <p>
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{}node_action&quot;&gt;
 *       &lt;attribute name=&quot;color&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 */
public interface CloudColorXmlActionType extends
		freemind.controller.actions.generated.instance.NodeAction {

	/**
	 * 
	 * @return possible object is {@link java.lang.String}
	 */
	java.lang.String getColor();

	/**
	 * 
	 * @param value
	 *            allowed object is {@link java.lang.String}
	 */
	void setColor(java.lang.String value);

}
